---
apiVersion: v1
kind: Namespace
metadata:
  name: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mysql
  name: deployment-mysql
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql-db
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mysql-db
    spec:
      containers:
      - image: public.ecr.aws/docker/library/mysql:8.0.36-bookworm
        imagePullPolicy: Always
        name: mysql80
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  namespace: mysql
  name: mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: mysql-db